// <auto-generated />
namespace BlogProjectWebApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class post_category_id : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(post_category_id));
        
        string IMigrationMetadata.Id
        {
            get { return "202210231424360_post_category_id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
